---
- name: create service for deployment  
  hosts: kubernetes
  # the playbook will run on ips under "kubernetes" group in the hosts file
  # become: true
  user: ubuntu
  
  tasks:
  - name: create a service
    command: kubectl apply -f valaxy-service.yml

