---
- name: create service for deployment  
  hosts: kubernetes
  # the playbook will run on ips under "kubernetes" group in the hosts file
  # become: true
  user: ubuntu
  
  tasks:
  - name: create a service
    # command: kubectl apply -f valaxy-service.yml
    # above is the path to the valaxy-service.yml file on kubernetes host, not on ansible host where this kubernetes-valaxy-service.yml file is running.
    command: kubectl apply -f ~/kubernetes/valaxy-service.yml

