apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: valaxy-devops-project
spec:
  selector:
    app: valaxy-devops-project
  type: LoadBalancer
  ports:
    - port: 8080 # this port is at pod level
      targetPort: 8080 # this ports is at kubernetes cluster level
      nodePort: 31200 # this port is for external access. The port should be exposed in AWS securtiy role associated with master instance.
